### ISSUE TITLE
Limited getBalance call for only one address

### ISSUE THREAD

**Issue by Johnaverse** [pinax-network/eos-evm-miner#16]
https://github.com/pinax-network/eos-evm-miner/blob/main/src/eth_getBalance.ts#LL5C5-L5C5

Metamask using batch of address to query all address balance at once. Limited getBalance call for only one address flow error
 
Error log
```
Received {"id":7321810095480698,"jsonrpc":"2.0","method":"eth_getBalance","params":["0x2293a13d4d812a845eb115a91f215ec20e1685ec","0x5d0468"]} undefined
```

**Comment by DenisCarriere** [comment]
Implementation doesn't allow multi-address requests

https://www.quicknode.com/docs/ethereum/eth_getBalance

Our implementation will always be using "latest" block, 2nd param is not needed for our usecase
