### ISSUE TITLE
remove default value of `--lock-genesis-time`

### ISSUE THREAD

**Issue by Johnaverse** [pinax-network/eos-evm-miner#17]
https://github.com/pinax-network/eos-evm-miner/blob/main/src/eth_blockNumber.ts

I am facing incorrect return value from miner endpoint. I think it is related to the wrong calculation within `eth_blockNumber.ts`. Metamask based on the latest block number to query tx count. Therefore, it related a incorrect value:

Request:
```
curl http://jungle4evm-arch41.mar.eosn.io:50305 -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":83}'
```

Result from miner:
```
{"jsonrpc":"2.0","id":83,"result":"0x5d1537"}
```

Result from rpc:
```
{"id":83,"jsonrpc":"2.0","result":"0x6e3d16"}
```

**Comment by DenisCarriere** [comment]
Oooh I know why!

You need to provide `--lock-genesis-time` flag

However, I believe it uses the default value of EOS Mainnet, which is causing a difference with Jungle

I'll remove the default value for those **locks**
