### ISSUE TITLE
Don't show all the internal URLs for a production deployment

### ISSUE THREAD

**Issue by matthewdarwin** [pinax-network/eos-evm-miner#19]
If we're running in "production" mode, I don't want to see all the internal URLs. https://jungle4.rpc.eosnation.io:8545/
Else I need to override this page so not leak internal info.

**Comment by DenisCarriere** [comment]
Agreed, yea I thought of that as well.

Can add a flag & .env to hide these endpoints by default

**Comment by DenisCarriere** [comment]
Using the following `.env` can disable displayed information in banner

```
# JSON RPC (optional)
SHOW_MINER=true
SHOW_ENDPOINTS=false
```

<img width="554" alt="image" src="https://github.com/pinax-network/eos-evm-miner/assets/550895/fa1f91bf-24b4-4a6a-a2e7-3a5dca160819">
