### ISSUE TITLE
🚀 Feature request: Count the number of transactions sent via eth_sendRawTransaction

### ISSUE THREAD

**Issue by Johnaverse** [pinax-network/eos-evm-miner#7]
- [ ] Add prometheus exporter
  - [ ] count the number of transactions sent via `eth_sendRawTransaction`

### About
Add prometheus exporter to the miner with count the number of transactions sent via eth_sendRawTransaction

### Is your proposal related to a problem?

Currently, there is no built-in functionality in the miner to count the number of transactions sent via the `eth_sendRawTransaction` function. This lack of visibility makes it challenging to track and analyse the transaction volume, which can be crucial for monitoring and optimising system performance.

### Describe the solution you'd like

I would like to propose the addition of a transaction counter feature to the miner. This feature would provide the capability to count the number of transactions sent using the `eth_sendRawTransaction` function. The transaction counter would increment every time a transaction is successfully sent, allowing users to accurately monitor and analyze the transaction volume over time.

### Describe alternatives you've considered

While there are alternative methods to count transactions sent via eth_sendRawTransaction, such as tracking events on chain event by the specific miner, these approaches can be cumbersome and time-consuming. Having an integrated transaction counter within the miner would offer a more convenient and efficient solution for users.

### Additional context

The transaction counter feature would significantly enhance the usability and monitoring capabilities of the miner. It would enable developers to gain insights into the transaction volume and assess the impact of changes or optimizations made to the system. This feature request aligns with the goal of providing users with valuable metrics and enhancing their ability to monitor and manage their EVM transactions effectively.

Please let me know if you need any further information or if there are any specific requirements for the feature request.

**Comment by DenisCarriere** [comment]
Added Prometheus metrics:

CLI
```
--metrics-listen-port <int>  The process will listen on this port for
                               Prometheus metrics requests (default: "9102")
```

`.env`

```env
# Prometheus Metrics
PROMETHEUS_PORT=9102
```
